services:
  foc-internal-nginx:
    container_name: "foc-internal-nginx"
    build:
      context: .
      dockerfile: docker/local/nginx/Dockerfile
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf:s
      - ./server/static:/app/static
    expose:
      - 8080

    ports:
      - "8080:8080"

    networks:
      - "foc-internal-server-nw"
      - "local-nginx-net"

  foc-internal-server:
    build:
      context: server
      dockerfile: Dockerfile
    image: foc-internal-server
    container_name: foc-internal-server
    volumes:
      - ./server:/server
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - "foc-internal-server-nw"
    #
  foc-internal-client:
    build:
      context: client
      dockerfile: Dockerfile
    image: foc-internal-client
    container_name: foc-internal-client
    volumes:
      - ./client:/client
    expose:
      - "3000"

    networks:
      - "foc-internal-server-nw"
    command: pnpm dev

networks:
  foc-internal-server-nw:
  local-nginx-net:
    external: true
