# Generated by Django 5.2.8 on 2025-12-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(100, 'Cancelled'), (10, 'Inspection Pending'), (11, 'Inspection Done'), (12, 'Inspection Review'), (20, 'Work Scheduled'), (21, 'Work Pending'), (30, 'In Progress'), (40, 'Work Finished'), (50, 'Completed')])),
                ('details', models.TextField(blank=True, null=True)),
                ('by_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('inspect_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspect_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verify_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IspectionFilesData',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.IntegerField(choices=[(0, 'Images'), (1, 'Video'), (3, 'Text')])),
                ('data', models.CharField(max_length=255)),
                ('inpection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
