# Generated by Django 5.2.8 on 2025-12-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='by_appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
