# Generated by Django 5.2.8 on 2025-12-01 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_alter_inspection_by_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
