# Generated by Django 5.2.8 on 2025-12-01 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_inspection_inspection_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inspection_date',
            new_name='inspection_finish',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspect_by',
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
