# Generated by Django 5.2.8 on 2025-12-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_rename_inspection_date_inspection_inspection_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
