# Generated by Django 5.2.8 on 2025-12-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_alter_inspection_inspection_finish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IspectionFilesData',
            new_name='InspectionFilesData',
        ),
    ]
