# Generated by Django 5.2.8 on 2025-12-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_rename_ispectionfilesdata_inspectionfilesdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionfilesdata',
            old_name='inpection',
            new_name='inspection',
        ),
    ]
