# Generated by Django 5.2.8 on 2025-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_rename_inpection_inspectionfilesdata_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
