# Generated by Django 5.2.8 on 2025-12-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_alter_inspection_inspection_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='by_appointment',
            new_name='appointment',
        ),
    ]
