# Generated by Django 5.2.8 on 2025-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_rename_by_appointment_inspection_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfilesdata',
            name='data',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
