# Generated by Django 5.2.8 on 2025-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_alter_inspectionfilesdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfilesdata',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'Images'), (1, 'Video'), (3, 'Text'), (4, 'Find')]),
        ),
    ]
