# Generated by Django 5.2.8 on 2025-12-02 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_alter_inspectionfilesdata_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfilesdata',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspectionsFilesData_set', to='inspection.inspection'),
        ),
    ]
