# Generated by Django 5.2.8 on 2025-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_alter_inspectionfilesdata_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfilesdata',
            name='data',
            field=models.FileField(upload_to='images/'),
        ),
    ]
