# Generated by Django 5.2.8 on 2025-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_alter_inspectionfilesdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionfilesdata',
            name='data',
        ),
        migrations.AddField(
            model_name='inspectionfilesdata',
            name='extension',
            field=models.CharField(default='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionfilesdata',
            name='file_data',
            field=models.CharField(default='img'),
            preserve_default=False,
        ),
    ]
