# Generated by Django 5.2.8 on 2025-12-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(100, 'Cancelled'), (10, 'Inspection Pending'), (11, 'Inspection Done'), (12, 'Inspection Review'), (20, 'Work Scheduled'), (21, 'Work Pending'), (30, 'In Progress'), (40, 'Work Finished'), (50, 'Completed')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.location')),
            ],
            options={
                'ordering': ['appointment_date__date', 'status', 'appointment_date__time'],
            },
        ),
    ]
