# Generated by Django 5.2.8 on 2025-11-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (10, 'Inspection Pending'), (11, 'Inspection Done'), (12, 'Inspection Review'), (20, 'Work Scheduled'), (21, 'Work Pending'), (30, 'In Progress'), (40, 'Work Finished'), (50, 'Completed')], default=0),
            preserve_default=False,
        ),
    ]
