# Generated by Django 5.2.8 on 2025-11-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date_time']},
        ),
    ]
