# Generated by Django 5.2.8 on 2025-11-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date_time',
            new_name='appointment_date',
        ),
    ]
