# Generated by Django 5.2.8 on 2025-11-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'status']},
        ),
    ]
