# Generated by Django 5.2.8 on 2025-11-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date__date', 'status', 'appointment_date__time']},
        ),
    ]
