# Generated by Django 5.2.8 on 2025-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(100, 'Cancelled'), (10, 'Inspection Pending'), (11, 'Inspection Done'), (12, 'Inspection Review'), (20, 'Work Scheduled'), (21, 'Work Pending'), (30, 'In Progress'), (40, 'Work Finished'), (50, 'Completed')]),
        ),
    ]
